"""add_phase_1_database_infrastructure

Revision ID: b04220c7278f
Revises: 004_chat
Create Date: 2026-07-13 14:37:17.341257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04220c7278f'
down_revision: Union[str, None] = '004_chat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_binaries',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('url_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('fetched_html', sa.Text(), nullable=True),
    sa.Column('parsed_markdown', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_image_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('binary_id', sa.String(length=64), nullable=False),
    sa.Column('url_resource_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('uploading', 'processing', 'processed', 'failed', name='document_status', create_type=False), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['binary_id'], ['document_binaries.sha256'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['url_resource_id'], ['url_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_binary_id'), 'document_versions', ['binary_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_url_resource_id'), 'document_versions', ['url_resource_id'], unique=False)
    op.create_table('document_structure_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('node_category', sa.String(length=50), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_structure_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_structure_nodes_document_version_id'), 'document_structure_nodes', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_structure_nodes_parent_id'), 'document_structure_nodes', ['parent_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_version_id'), 'processing_jobs', ['document_version_id'], unique=False)
    op.add_column('document_chunks', sa.Column('document_version_id', sa.UUID(), nullable=True))
    op.add_column('document_chunks', sa.Column('structure_node_id', sa.UUID(), nullable=True))
    op.add_column('document_chunks', sa.Column('char_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('char_end', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('char_count', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('hash', sa.String(length=64), nullable=True))
    op.add_column('document_chunks', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_id'), 'document_chunks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_structure_node_id'), 'document_chunks', ['structure_node_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'document_structure_nodes', ['structure_node_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'document_chunks', 'document_chunks', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_chunks', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_structure_node_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_parent_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'parent_id')
    op.drop_column('document_chunks', 'hash')
    op.drop_column('document_chunks', 'word_count')
    op.drop_column('document_chunks', 'char_count')
    op.drop_column('document_chunks', 'token_count')
    op.drop_column('document_chunks', 'char_end')
    op.drop_column('document_chunks', 'char_start')
    op.drop_column('document_chunks', 'structure_node_id')
    op.drop_column('document_chunks', 'document_version_id')
    op.drop_index(op.f('ix_processing_jobs_document_version_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_document_structure_nodes_parent_id'), table_name='document_structure_nodes')
    op.drop_index(op.f('ix_document_structure_nodes_document_version_id'), table_name='document_structure_nodes')
    op.drop_table('document_structure_nodes')
    op.drop_index(op.f('ix_document_versions_url_resource_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_binary_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('url_resources')
    op.drop_table('document_binaries')
    # ### end Alembic commands ###
