from enum import Enum

class NodeType(str, Enum):
    DOCUMENT = "DOCUMENT"
    TITLE = "TITLE"
    HEADING_1 = "heading_1"
    HEADING_2 = "heading_2"
    HEADING_3 = "heading_3"
    HEADING_4 = "heading_4"
    HEADING_5 = "heading_5"
    HEADING_6 = "heading_6"
    SECTION = "SECTION"
    SUBSECTION = "SUBSECTION"
    PARAGRAPH = "PARAGRAPH"
    BULLET_LIST = "BULLET_LIST"
    NUMBERED_LIST = "NUMBERED_LIST"
    TABLE = "TABLE"
    TABLE_ROW = "TABLE_ROW"
    TABLE_CELL = "TABLE_CELL"
    CODE_BLOCK = "CODE_BLOCK"
    INLINE_CODE = "INLINE_CODE"
    QUOTE = "QUOTE"
    FORMULA = "FORMULA"
    IMAGE = "IMAGE"
    CAPTION = "CAPTION"
    FOOTNOTE = "FOOTNOTE"
    UNKNOWN = "UNKNOWN"
