"""
Default configuration constants for AI Providers
"""
from typing import Dict, Any

DEFAULT_PROVIDER_MODELS = {
    "openai": {
        "chat": "gpt-4o",
        "document_qa": "gpt-4o",
        "rag_search": "gpt-4o",
        "summarization": "gpt-4o-mini",
        "reasoning": "gpt-4o",
        "code_explanation": "gpt-4o",
        "code_generation": "gpt-4o",
        "embedding": "text-embedding-3-small",
        "default": "gpt-4o"
    },
    "gemini": {
        "chat": "gemini-2.5-flash",
        "document_qa": "gemini-2.5-flash",
        "document_analysis": "gemini-2.5-flash",
        "summarization": "gemini-2.5-flash",
        "reasoning": "gemini-2.5-flash",
        "default": "gemini-2.5-flash"
    },
    "groq": {
        "chat": "llama-3.3-70b-versatile",
        "summarization": "llama-3.3-70b-versatile",
        "reasoning": "llama-3.3-70b-versatile",
        "title_generation": "llama-3.1-8b-instant",
        "tag_generation": "llama-3.1-8b-instant",
        "default": "llama-3.3-70b-versatile"
    },
    "ollama": {
        "chat": "qwen2.5:7b",
        "document_qa": "qwen2.5:7b",
        "keyword_extraction": "qwen2.5:7b",
        "embedding": "nomic-embed-text",
        "default": "qwen2.5:7b"
    },
    "openrouter": {
        "chat": "meta-llama/llama-3.3-70b-instruct",
        "reasoning": "meta-llama/llama-3.3-70b-instruct",
        "default": "meta-llama/llama-3.3-70b-instruct"
    }
}

DEFAULT_TIMEOUTS = {
    "openai": 30.0,
    "gemini": 30.0,
    "groq": 20.0,
    "openrouter": 35.0,
    "ollama": 60.0
}

DEFAULT_RETRY_LIMITS = {
    "openai": 2,
    "gemini": 2,
    "groq": 2,
    "openrouter": 2,
    "ollama": 1
}

DEFAULT_PROVIDER_PROFILES: Dict[str, Dict[str, Any]] = {
    "openai": {
        "provider_id": "openai",
        "display_name": "OpenAI",
        "description": "Industry standard OpenAI models (GPT-4o, GPT-4o-mini, o3-mini)",
        "priority": 10,
        "enabled": True,
        "api_key_name": "OPENAI_API_KEY",
        "default_model": "gpt-4o",
        "supported_models": ["gpt-4o", "gpt-4o-mini", "o3-mini", "text-embedding-3-small"],
        "capabilities": ["chat", "document_qa", "rag_search", "code_generation", "code_explanation", "code_review", "reasoning", "embedding", "summarization"],
        "supports_chat": True,
        "supports_reasoning": True,
        "supports_rag": True,
        "supports_embeddings": True,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_json": True,
        "supports_vision": True,
        "supports_images": True,
        "supports_multimodal": True,
        "supports_function_calling": True,
        "max_context_tokens": 128000,
        "max_output_tokens": 4096,
        "timeout": 30.0,
        "cooldown": 60.0,
        "retry_limit": 2,
        "cost_level": "high",
        "speed_level": "fast",
        "quality_level": "high",
        "free_tier": False,
        "online": True,
        "local": False,
        "group": "cloud",
        "website_url": "https://openai.com",
        "doc_url": "https://platform.openai.com/docs",
        "api_version": "v1",
        "provider_version": "1.0.0",
        "maintainer": "OpenAI",
        "plugin_version": "1.0.0"
    },
    "gemini": {
        "provider_id": "gemini",
        "display_name": "Google Gemini",
        "description": "Google Gemini models with large context window (Gemini 2.5 Flash, 1.5 Pro)",
        "priority": 20,
        "enabled": True,
        "api_key_name": "GEMINI_API_KEY",
        "default_model": "gemini-2.5-flash",
        "supported_models": ["gemini-2.5-flash", "gemini-1.5-pro"],
        "capabilities": ["chat", "document_qa", "document_analysis", "summarization", "rag_search", "code_explanation", "translation"],
        "supports_chat": True,
        "supports_reasoning": True,
        "supports_rag": True,
        "supports_embeddings": False,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_json": True,
        "supports_vision": True,
        "supports_images": True,
        "supports_multimodal": True,
        "supports_function_calling": True,
        "max_context_tokens": 1000000,
        "max_output_tokens": 8192,
        "timeout": 30.0,
        "cooldown": 60.0,
        "retry_limit": 2,
        "cost_level": "medium",
        "speed_level": "fast",
        "quality_level": "high",
        "free_tier": False,
        "online": True,
        "local": False,
        "group": "cloud",
        "website_url": "https://ai.google.dev",
        "doc_url": "https://ai.google.dev/docs",
        "api_version": "v1beta",
        "provider_version": "1.0.0",
        "maintainer": "Google AI",
        "plugin_version": "1.0.0"
    },
    "groq": {
        "provider_id": "groq",
        "display_name": "Groq Cloud",
        "description": "Ultra-fast LPU inference engine for open models",
        "priority": 15,
        "enabled": True,
        "api_key_name": "GROQ_API_KEY",
        "base_url": "https://api.groq.com/openai/v1",
        "default_model": "llama-3.3-70b-versatile",
        "supported_models": ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
        "capabilities": ["chat", "summarization", "reasoning", "title_generation", "tag_generation", "translation", "code_generation"],
        "supports_chat": True,
        "supports_reasoning": True,
        "supports_rag": True,
        "supports_embeddings": False,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_json": True,
        "supports_vision": False,
        "supports_multimodal": False,
        "supports_function_calling": True,
        "max_context_tokens": 128000,
        "max_output_tokens": 4096,
        "timeout": 20.0,
        "cooldown": 60.0,
        "retry_limit": 2,
        "cost_level": "low",
        "speed_level": "fast",
        "quality_level": "high",
        "free_tier": False,
        "online": True,
        "local": False,
        "group": "cloud",
        "website_url": "https://groq.com",
        "doc_url": "https://console.groq.com/docs",
        "api_version": "v1",
        "provider_version": "1.0.0",
        "maintainer": "Groq Inc",
        "plugin_version": "1.0.0"
    },
    "ollama": {
        "provider_id": "ollama",
        "display_name": "Ollama Local",
        "description": "Local privacy-first open source model engine",
        "priority": 30,
        "enabled": True,
        "api_key_name": None,
        "base_url": "http://localhost:11434",
        "default_model": "qwen2.5:7b",
        "supported_models": ["qwen2.5:7b", "llama3.1:8b", "nomic-embed-text"],
        "capabilities": ["chat", "document_qa", "keyword_extraction", "tag_generation", "classification", "embedding"],
        "supports_chat": True,
        "supports_reasoning": True,
        "supports_rag": True,
        "supports_embeddings": True,
        "supports_streaming": True,
        "supports_tools": False,
        "supports_json": True,
        "supports_vision": False,
        "supports_multimodal": False,
        "supports_function_calling": False,
        "max_context_tokens": 32768,
        "max_output_tokens": 2048,
        "timeout": 60.0,
        "cooldown": 60.0,
        "retry_limit": 1,
        "cost_level": "free",
        "speed_level": "medium",
        "quality_level": "medium",
        "free_tier": True,
        "online": False,
        "local": True,
        "group": "local",
        "website_url": "https://ollama.ai",
        "doc_url": "https://github.com/ollama/ollama/blob/main/docs/api.md",
        "api_version": "v1",
        "provider_version": "1.0.0",
        "maintainer": "Ollama Team",
        "plugin_version": "1.0.0"
    },
    "openrouter": {
        "provider_id": "openrouter",
        "display_name": "OpenRouter Unified API",
        "description": "Unified gateway to hundreds of open and proprietary AI models",
        "priority": 25,
        "enabled": True,
        "api_key_name": "OPENROUTER_API_KEY",
        "base_url": "https://openrouter.ai/api/v1",
        "default_model": "meta-llama/llama-3.3-70b-instruct",
        "supported_models": ["meta-llama/llama-3.3-70b-instruct", "anthropic/claude-3.5-sonnet", "deepseek/deepseek-r1"],
        "capabilities": ["chat", "document_qa", "reasoning", "rag_search", "summarization", "code_generation"],
        "supports_chat": True,
        "supports_reasoning": True,
        "supports_rag": True,
        "supports_embeddings": False,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_json": True,
        "supports_vision": True,
        "supports_multimodal": True,
        "supports_function_calling": True,
        "max_context_tokens": 200000,
        "max_output_tokens": 4096,
        "timeout": 35.0,
        "cooldown": 60.0,
        "retry_limit": 2,
        "cost_level": "medium",
        "speed_level": "medium",
        "quality_level": "high",
        "free_tier": False,
        "online": True,
        "local": False,
        "group": "cloud",
        "website_url": "https://openrouter.ai",
        "doc_url": "https://openrouter.ai/docs",
        "api_version": "v1",
        "provider_version": "1.0.0",
        "maintainer": "OpenRouter",
        "plugin_version": "1.0.0"
    }
}
